
-- ═══════════════════════════════════════════════════════════════
-- MG3003 — Seed weeks 2-10 custom scenarios
-- Run this in Supabase Dashboard → SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- 1. Add week column (if not exists)
ALTER TABLE custom_scenarios ADD COLUMN IF NOT EXISTS week_number INTEGER DEFAULT 1;
ALTER TABLE classroom_runs ADD COLUMN IF NOT EXISTS active_week INTEGER DEFAULT 1;
UPDATE classroom_runs SET active_week = 1 WHERE active_week IS NULL;


-- ═══════════════════════════════════════
-- WEEK 2: Digital Transformation & HRTech
-- ═══════════════════════════════════════

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Workforce Planning', 'Cloud HRMS migration decision', 'GlobalTech's legacy on-premise HRIS (PeopleSoft 9.2) is end-of-life. The board wants a cloud migration plan.', '[{"text": "Unified cloud HCM suite (Workday/SuccessFactors) with phased 12-month migration", "flow": "Workforce Planning -> HRIS -> Recruitment", "impact": {"hrEfficiency": 12, "talentQuality": 5, "budgetHealth": -12, "legalSafety": 3}}, {"text": "Custom middleware layer to extend legacy system by 3 more years", "flow": "Workforce Planning -> IT -> Compliance", "impact": {"budgetHealth": 5, "legalSafety": -5, "hrEfficiency": -8}}, {"text": "Migrate only Core HR + Payroll to cloud first, defer Talent modules", "flow": "Workforce Planning -> HRIS -> Payroll", "impact": {"hrEfficiency": 6, "budgetHealth": -6, "talentQuality": 2, "employeeTrust": 3}}]', 2, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Recruitment', 'AI-powered candidate screening backlash', 'AI screener shortlisted 3x faster but 40% of rejected candidates from underrepresented groups filed complaints.', '[{"text": "Pause AI tool, audit training data, implement fairness guardrails", "flow": "Recruitment -> Compliance -> Employee Relations", "impact": {"employeeTrust": 10, "legalSafety": 8, "hrEfficiency": -5, "talentQuality": 3}}, {"text": "Defend the tool, add manual appeal process", "flow": "Recruitment -> Legal -> PR", "impact": {"hrEfficiency": 6, "legalSafety": -8, "employeeTrust": -10}}, {"text": "Replace with structured work-sample tests for all candidates", "flow": "Recruitment -> Performance -> L&D", "impact": {"talentQuality": 8, "hrEfficiency": -3, "budgetHealth": -4, "employeeTrust": 5}}]', 2, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Onboarding', 'Remote onboarding failing globally', '200 new hires across 12 countries — 30% who left within 60 days cite confusing onboarding.', '[{"text": "Unified digital onboarding portal with country-specific compliance + buddy system", "flow": "Onboarding -> HRIS -> Compliance", "impact": {"employeeTrust": 12, "hrEfficiency": 7, "legalSafety": 5, "budgetHealth": -5}}, {"text": "Standardized PDF packet + mandatory Zoom orientation", "flow": "Onboarding -> Compliance", "impact": {"hrEfficiency": 4, "legalSafety": -3, "employeeTrust": -6, "talentQuality": -2}}, {"text": "Outsource onboarding to BPO firm for compliance paperwork", "flow": "Onboarding -> Vendor Mgmt -> Payroll", "impact": {"hrEfficiency": 5, "budgetHealth": -6, "legalSafety": -4, "employeeTrust": -3}}]', 2, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Payroll', 'Multi-country payroll consolidation', '6 separate payroll systems across 30 countries. Reconciliation takes 8 business days, error rate 4%.', '[{"text": "Single global payroll platform (CloudPay/ADP) with unified reporting", "flow": "Payroll -> HRIS -> Finance", "impact": {"hrEfficiency": 12, "legalSafety": 6, "budgetHealth": -15, "employeeTrust": 4}}, {"text": "Payroll data warehouse consolidating reports from all 6 systems", "flow": "Payroll -> IT -> Analytics", "impact": {"hrEfficiency": 5, "budgetHealth": -4, "legalSafety": 2, "talentQuality": 3}}, {"text": "Standardize pay codes and tax rules across all 6 systems", "flow": "Payroll -> Compliance -> Finance", "impact": {"hrEfficiency": 4, "legalSafety": 5, "budgetHealth": -3, "employeeTrust": 2}}]', 2, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Performance', 'OKR roll-out met with resistance', 'CHRO wants quarterly OKRs. Managers say it's more admin work. Engineering VPs pushing back.', '[{"text": "Pilot with 3 departments first, collect productivity data", "flow": "Performance -> Analytics -> L&D", "impact": {"employeeTrust": 6, "talentQuality": 5, "hrEfficiency": -3, "budgetHealth": -2}}, {"text": "Full roll-out with mandatory manager training, 6-month adjustment", "flow": "Performance -> L&D -> Employee Relations", "impact": {"talentQuality": 8, "hrEfficiency": -6, "employeeTrust": -4, "budgetHealth": -3}}, {"text": "Keep annual review, add mid-year check-in only", "flow": "Performance -> Employee Relations", "impact": {"employeeTrust": 3, "hrEfficiency": 2, "talentQuality": -2, "budgetHealth": 1}}]', 2, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('L&D', 'Skills gap in AI and data engineering', '60% of current engineers lack cloud/AI skills for next-gen product roadmap.', '[{"text": "Internal AI Academy with projects, certifications, mentorship", "flow": "L&D -> Talent -> Performance", "impact": {"talentQuality": 12, "employeeTrust": 8, "hrEfficiency": -3, "budgetHealth": -8}}, {"text": "Hire externally for top 20%, retention bonuses for critical staff", "flow": "L&D -> Recruitment -> Finance", "impact": {"talentQuality": 6, "budgetHealth": -10, "employeeTrust": -3, "hrEfficiency": 2}}, {"text": "Coursera for Business with learning budgets and time allocation", "flow": "L&D -> Vendor Mgmt -> Performance", "impact": {"talentQuality": 5, "employeeTrust": 4, "budgetHealth": -3, "hrEfficiency": 1}}]', 2, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Compliance', 'GDPR audit reveals data gaps', '15% of employee records lack proper consent. Data retention policies not enforced across 8 countries.', '[{"text": "Company-wide data hygiene: re-consent, automate retention, quarterly audits", "flow": "Compliance -> HRIS -> Employee Relations", "impact": {"legalSafety": 14, "employeeTrust": 4, "hrEfficiency": -5, "budgetHealth": -6}}, {"text": "Fix only the 8 flagged countries, document rest as future plan", "flow": "Compliance -> Legal", "impact": {"legalSafety": 5, "budgetHealth": -2, "hrEfficiency": 2, "employeeTrust": -3}}, {"text": "Data privacy dashboard automating consent tracking and retention", "flow": "Compliance -> HRIS -> Analytics", "impact": {"legalSafety": 10, "hrEfficiency": 6, "budgetHealth": -5, "employeeTrust": 3}}]', 2, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Employee Relations', 'Hybrid work policy creating tension', 'Remote employees feel left out of promotions. Office staff resent flexibility gap. 3 formal grievances.', '[{"text": "Transparent hybrid policy: 3 days office, clear promotion criteria, async norms", "flow": "Employee Relations -> Policy -> Performance", "impact": {"employeeTrust": 10, "hrEfficiency": 4, "talentQuality": 3, "legalSafety": 5}}, {"text": "Let each team decide their own hybrid model with minimum guidelines", "flow": "Employee Relations -> Team Leads", "impact": {"employeeTrust": 3, "hrEfficiency": -2, "talentQuality": -4, "legalSafety": -3}}, {"text": "Go fully remote-first, close 2 offices, invest in tools, quarterly offsites", "flow": "Employee Relations -> Finance -> HRIS", "impact": {"budgetHealth": 8, "employeeTrust": 5, "talentQuality": -3, "hrEfficiency": -2}}]', 2, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Capstone', 'HRIS vendor selection final presentation', 'Board needs vendor recommendation. Workday, SAP SuccessFactors, Oracle HCM Cloud are finalists.', '[{"text": "Workday: best UX, unified finance+HR, fastest time-to-value", "flow": "Capstone -> HRIS -> Finance", "impact": {"hrEfficiency": 10, "employeeTrust": 6, "budgetHealth": -8, "talentQuality": 5}}, {"text": "SAP SuccessFactors: best global compliance, SAP ERP integration", "flow": "Capstone -> HRIS -> Compliance", "impact": {"legalSafety": 10, "talentQuality": 5, "hrEfficiency": 5, "budgetHealth": -10}}, {"text": "Oracle HCM Cloud: strongest payroll, best analytics, longer deployment", "flow": "Capstone -> HRIS -> Analytics", "impact": {"talentQuality": 8, "hrEfficiency": 6, "budgetHealth": -12, "legalSafety": 4}}]', 2, (SELECT id FROM auth.users LIMIT 1));


-- ═══════════════════════════════════════
-- WEEK 5: Talent Analytics & Workforce Planning
-- ═══════════════════════════════════════

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Workforce Planning', 'Workforce Planning challenge (data-driven)', 'GlobalTech faces a data-driven challenge in Workforce Planning. Your team must analyze and respond.', '[{"text": "Build a comprehensive data-driven solution for Workforce Planning", "flow": "Workforce Planning -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Workforce Planning to a specialist vendor", "flow": "Workforce Planning -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Workforce Planning as-is, document improvement plan for next quarter", "flow": "Workforce Planning -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 5, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Recruitment', 'Recruitment challenge (data-driven)', 'GlobalTech faces a data-driven challenge in Recruitment. Your team must analyze and respond.', '[{"text": "Build a comprehensive data-driven solution for Recruitment", "flow": "Recruitment -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Recruitment to a specialist vendor", "flow": "Recruitment -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Recruitment as-is, document improvement plan for next quarter", "flow": "Recruitment -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 5, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Onboarding', 'Onboarding challenge (data-driven)', 'GlobalTech faces a data-driven challenge in Onboarding. Your team must analyze and respond.', '[{"text": "Build a comprehensive data-driven solution for Onboarding", "flow": "Onboarding -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Onboarding to a specialist vendor", "flow": "Onboarding -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Onboarding as-is, document improvement plan for next quarter", "flow": "Onboarding -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 5, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Payroll', 'Payroll challenge (data-driven)', 'GlobalTech faces a data-driven challenge in Payroll. Your team must analyze and respond.', '[{"text": "Build a comprehensive data-driven solution for Payroll", "flow": "Payroll -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Payroll to a specialist vendor", "flow": "Payroll -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Payroll as-is, document improvement plan for next quarter", "flow": "Payroll -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 5, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Performance', 'Performance challenge (data-driven)', 'GlobalTech faces a data-driven challenge in Performance. Your team must analyze and respond.', '[{"text": "Build a comprehensive data-driven solution for Performance", "flow": "Performance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Performance to a specialist vendor", "flow": "Performance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Performance as-is, document improvement plan for next quarter", "flow": "Performance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 5, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('L&D', 'L&D challenge (data-driven)', 'GlobalTech faces a data-driven challenge in L&D. Your team must analyze and respond.', '[{"text": "Build a comprehensive data-driven solution for L&D", "flow": "L&D -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource L&D to a specialist vendor", "flow": "L&D -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run L&D as-is, document improvement plan for next quarter", "flow": "L&D -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 5, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Compliance', 'Compliance challenge (data-driven)', 'GlobalTech faces a data-driven challenge in Compliance. Your team must analyze and respond.', '[{"text": "Build a comprehensive data-driven solution for Compliance", "flow": "Compliance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Compliance to a specialist vendor", "flow": "Compliance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Compliance as-is, document improvement plan for next quarter", "flow": "Compliance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 5, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Employee Relations', 'Employee Relations challenge (data-driven)', 'GlobalTech faces a data-driven challenge in Employee Relations. Your team must analyze and respond.', '[{"text": "Build a comprehensive data-driven solution for Employee Relations", "flow": "Employee Relations -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Employee Relations to a specialist vendor", "flow": "Employee Relations -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Employee Relations as-is, document improvement plan for next quarter", "flow": "Employee Relations -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 5, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Capstone', 'Capstone challenge (data-driven)', 'GlobalTech faces a data-driven challenge in Capstone. Your team must analyze and respond.', '[{"text": "Build a comprehensive data-driven solution for Capstone", "flow": "Capstone -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Capstone to a specialist vendor", "flow": "Capstone -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Capstone as-is, document improvement plan for next quarter", "flow": "Capstone -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 5, (SELECT id FROM auth.users LIMIT 1));


-- ═══════════════════════════════════════
-- WEEK 6: Employee Experience & Culture
-- ═══════════════════════════════════════

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Workforce Planning', 'Workforce Planning challenge (culture-first)', 'GlobalTech faces a culture-first challenge in Workforce Planning. Your team must analyze and respond.', '[{"text": "Build a comprehensive culture-first solution for Workforce Planning", "flow": "Workforce Planning -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Workforce Planning to a specialist vendor", "flow": "Workforce Planning -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Workforce Planning as-is, document improvement plan for next quarter", "flow": "Workforce Planning -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 6, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Recruitment', 'Recruitment challenge (culture-first)', 'GlobalTech faces a culture-first challenge in Recruitment. Your team must analyze and respond.', '[{"text": "Build a comprehensive culture-first solution for Recruitment", "flow": "Recruitment -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Recruitment to a specialist vendor", "flow": "Recruitment -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Recruitment as-is, document improvement plan for next quarter", "flow": "Recruitment -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 6, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Onboarding', 'Onboarding challenge (culture-first)', 'GlobalTech faces a culture-first challenge in Onboarding. Your team must analyze and respond.', '[{"text": "Build a comprehensive culture-first solution for Onboarding", "flow": "Onboarding -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Onboarding to a specialist vendor", "flow": "Onboarding -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Onboarding as-is, document improvement plan for next quarter", "flow": "Onboarding -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 6, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Payroll', 'Payroll challenge (culture-first)', 'GlobalTech faces a culture-first challenge in Payroll. Your team must analyze and respond.', '[{"text": "Build a comprehensive culture-first solution for Payroll", "flow": "Payroll -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Payroll to a specialist vendor", "flow": "Payroll -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Payroll as-is, document improvement plan for next quarter", "flow": "Payroll -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 6, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Performance', 'Performance challenge (culture-first)', 'GlobalTech faces a culture-first challenge in Performance. Your team must analyze and respond.', '[{"text": "Build a comprehensive culture-first solution for Performance", "flow": "Performance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Performance to a specialist vendor", "flow": "Performance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Performance as-is, document improvement plan for next quarter", "flow": "Performance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 6, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('L&D', 'L&D challenge (culture-first)', 'GlobalTech faces a culture-first challenge in L&D. Your team must analyze and respond.', '[{"text": "Build a comprehensive culture-first solution for L&D", "flow": "L&D -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource L&D to a specialist vendor", "flow": "L&D -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run L&D as-is, document improvement plan for next quarter", "flow": "L&D -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 6, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Compliance', 'Compliance challenge (culture-first)', 'GlobalTech faces a culture-first challenge in Compliance. Your team must analyze and respond.', '[{"text": "Build a comprehensive culture-first solution for Compliance", "flow": "Compliance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Compliance to a specialist vendor", "flow": "Compliance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Compliance as-is, document improvement plan for next quarter", "flow": "Compliance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 6, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Employee Relations', 'Employee Relations challenge (culture-first)', 'GlobalTech faces a culture-first challenge in Employee Relations. Your team must analyze and respond.', '[{"text": "Build a comprehensive culture-first solution for Employee Relations", "flow": "Employee Relations -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Employee Relations to a specialist vendor", "flow": "Employee Relations -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Employee Relations as-is, document improvement plan for next quarter", "flow": "Employee Relations -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 6, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Capstone', 'Capstone challenge (culture-first)', 'GlobalTech faces a culture-first challenge in Capstone. Your team must analyze and respond.', '[{"text": "Build a comprehensive culture-first solution for Capstone", "flow": "Capstone -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Capstone to a specialist vendor", "flow": "Capstone -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Capstone as-is, document improvement plan for next quarter", "flow": "Capstone -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 6, (SELECT id FROM auth.users LIMIT 1));


-- ═══════════════════════════════════════
-- WEEK 7: Compensation & Benefits Strategy
-- ═══════════════════════════════════════

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Workforce Planning', 'Workforce Planning challenge (comp-focused)', 'GlobalTech faces a comp-focused challenge in Workforce Planning. Your team must analyze and respond.', '[{"text": "Build a comprehensive comp-focused solution for Workforce Planning", "flow": "Workforce Planning -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Workforce Planning to a specialist vendor", "flow": "Workforce Planning -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Workforce Planning as-is, document improvement plan for next quarter", "flow": "Workforce Planning -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 7, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Recruitment', 'Recruitment challenge (comp-focused)', 'GlobalTech faces a comp-focused challenge in Recruitment. Your team must analyze and respond.', '[{"text": "Build a comprehensive comp-focused solution for Recruitment", "flow": "Recruitment -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Recruitment to a specialist vendor", "flow": "Recruitment -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Recruitment as-is, document improvement plan for next quarter", "flow": "Recruitment -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 7, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Onboarding', 'Onboarding challenge (comp-focused)', 'GlobalTech faces a comp-focused challenge in Onboarding. Your team must analyze and respond.', '[{"text": "Build a comprehensive comp-focused solution for Onboarding", "flow": "Onboarding -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Onboarding to a specialist vendor", "flow": "Onboarding -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Onboarding as-is, document improvement plan for next quarter", "flow": "Onboarding -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 7, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Payroll', 'Payroll challenge (comp-focused)', 'GlobalTech faces a comp-focused challenge in Payroll. Your team must analyze and respond.', '[{"text": "Build a comprehensive comp-focused solution for Payroll", "flow": "Payroll -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Payroll to a specialist vendor", "flow": "Payroll -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Payroll as-is, document improvement plan for next quarter", "flow": "Payroll -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 7, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Performance', 'Performance challenge (comp-focused)', 'GlobalTech faces a comp-focused challenge in Performance. Your team must analyze and respond.', '[{"text": "Build a comprehensive comp-focused solution for Performance", "flow": "Performance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Performance to a specialist vendor", "flow": "Performance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Performance as-is, document improvement plan for next quarter", "flow": "Performance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 7, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('L&D', 'L&D challenge (comp-focused)', 'GlobalTech faces a comp-focused challenge in L&D. Your team must analyze and respond.', '[{"text": "Build a comprehensive comp-focused solution for L&D", "flow": "L&D -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource L&D to a specialist vendor", "flow": "L&D -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run L&D as-is, document improvement plan for next quarter", "flow": "L&D -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 7, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Compliance', 'Compliance challenge (comp-focused)', 'GlobalTech faces a comp-focused challenge in Compliance. Your team must analyze and respond.', '[{"text": "Build a comprehensive comp-focused solution for Compliance", "flow": "Compliance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Compliance to a specialist vendor", "flow": "Compliance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Compliance as-is, document improvement plan for next quarter", "flow": "Compliance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 7, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Employee Relations', 'Employee Relations challenge (comp-focused)', 'GlobalTech faces a comp-focused challenge in Employee Relations. Your team must analyze and respond.', '[{"text": "Build a comprehensive comp-focused solution for Employee Relations", "flow": "Employee Relations -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Employee Relations to a specialist vendor", "flow": "Employee Relations -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Employee Relations as-is, document improvement plan for next quarter", "flow": "Employee Relations -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 7, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Capstone', 'Capstone challenge (comp-focused)', 'GlobalTech faces a comp-focused challenge in Capstone. Your team must analyze and respond.', '[{"text": "Build a comprehensive comp-focused solution for Capstone", "flow": "Capstone -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Capstone to a specialist vendor", "flow": "Capstone -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Capstone as-is, document improvement plan for next quarter", "flow": "Capstone -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 7, (SELECT id FROM auth.users LIMIT 1));


-- ═══════════════════════════════════════
-- WEEK 8: HRIS Security & Data Privacy
-- ═══════════════════════════════════════

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Workforce Planning', 'Workforce Planning challenge (security-first)', 'GlobalTech faces a security-first challenge in Workforce Planning. Your team must analyze and respond.', '[{"text": "Build a comprehensive security-first solution for Workforce Planning", "flow": "Workforce Planning -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Workforce Planning to a specialist vendor", "flow": "Workforce Planning -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Workforce Planning as-is, document improvement plan for next quarter", "flow": "Workforce Planning -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 8, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Recruitment', 'Recruitment challenge (security-first)', 'GlobalTech faces a security-first challenge in Recruitment. Your team must analyze and respond.', '[{"text": "Build a comprehensive security-first solution for Recruitment", "flow": "Recruitment -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Recruitment to a specialist vendor", "flow": "Recruitment -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Recruitment as-is, document improvement plan for next quarter", "flow": "Recruitment -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 8, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Onboarding', 'Onboarding challenge (security-first)', 'GlobalTech faces a security-first challenge in Onboarding. Your team must analyze and respond.', '[{"text": "Build a comprehensive security-first solution for Onboarding", "flow": "Onboarding -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Onboarding to a specialist vendor", "flow": "Onboarding -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Onboarding as-is, document improvement plan for next quarter", "flow": "Onboarding -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 8, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Payroll', 'Payroll challenge (security-first)', 'GlobalTech faces a security-first challenge in Payroll. Your team must analyze and respond.', '[{"text": "Build a comprehensive security-first solution for Payroll", "flow": "Payroll -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Payroll to a specialist vendor", "flow": "Payroll -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Payroll as-is, document improvement plan for next quarter", "flow": "Payroll -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 8, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Performance', 'Performance challenge (security-first)', 'GlobalTech faces a security-first challenge in Performance. Your team must analyze and respond.', '[{"text": "Build a comprehensive security-first solution for Performance", "flow": "Performance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Performance to a specialist vendor", "flow": "Performance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Performance as-is, document improvement plan for next quarter", "flow": "Performance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 8, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('L&D', 'L&D challenge (security-first)', 'GlobalTech faces a security-first challenge in L&D. Your team must analyze and respond.', '[{"text": "Build a comprehensive security-first solution for L&D", "flow": "L&D -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource L&D to a specialist vendor", "flow": "L&D -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run L&D as-is, document improvement plan for next quarter", "flow": "L&D -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 8, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Compliance', 'Compliance challenge (security-first)', 'GlobalTech faces a security-first challenge in Compliance. Your team must analyze and respond.', '[{"text": "Build a comprehensive security-first solution for Compliance", "flow": "Compliance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Compliance to a specialist vendor", "flow": "Compliance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Compliance as-is, document improvement plan for next quarter", "flow": "Compliance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 8, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Employee Relations', 'Employee Relations challenge (security-first)', 'GlobalTech faces a security-first challenge in Employee Relations. Your team must analyze and respond.', '[{"text": "Build a comprehensive security-first solution for Employee Relations", "flow": "Employee Relations -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Employee Relations to a specialist vendor", "flow": "Employee Relations -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Employee Relations as-is, document improvement plan for next quarter", "flow": "Employee Relations -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 8, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Capstone', 'Capstone challenge (security-first)', 'GlobalTech faces a security-first challenge in Capstone. Your team must analyze and respond.', '[{"text": "Build a comprehensive security-first solution for Capstone", "flow": "Capstone -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Capstone to a specialist vendor", "flow": "Capstone -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Capstone as-is, document improvement plan for next quarter", "flow": "Capstone -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 8, (SELECT id FROM auth.users LIMIT 1));


-- ═══════════════════════════════════════
-- WEEK 9: Future of Work & AI in HR
-- ═══════════════════════════════════════

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Workforce Planning', 'Workforce Planning challenge (AI-forward)', 'GlobalTech faces a AI-forward challenge in Workforce Planning. Your team must analyze and respond.', '[{"text": "Build a comprehensive AI-forward solution for Workforce Planning", "flow": "Workforce Planning -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Workforce Planning to a specialist vendor", "flow": "Workforce Planning -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Workforce Planning as-is, document improvement plan for next quarter", "flow": "Workforce Planning -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 9, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Recruitment', 'Recruitment challenge (AI-forward)', 'GlobalTech faces a AI-forward challenge in Recruitment. Your team must analyze and respond.', '[{"text": "Build a comprehensive AI-forward solution for Recruitment", "flow": "Recruitment -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Recruitment to a specialist vendor", "flow": "Recruitment -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Recruitment as-is, document improvement plan for next quarter", "flow": "Recruitment -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 9, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Onboarding', 'Onboarding challenge (AI-forward)', 'GlobalTech faces a AI-forward challenge in Onboarding. Your team must analyze and respond.', '[{"text": "Build a comprehensive AI-forward solution for Onboarding", "flow": "Onboarding -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Onboarding to a specialist vendor", "flow": "Onboarding -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Onboarding as-is, document improvement plan for next quarter", "flow": "Onboarding -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 9, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Payroll', 'Payroll challenge (AI-forward)', 'GlobalTech faces a AI-forward challenge in Payroll. Your team must analyze and respond.', '[{"text": "Build a comprehensive AI-forward solution for Payroll", "flow": "Payroll -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Payroll to a specialist vendor", "flow": "Payroll -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Payroll as-is, document improvement plan for next quarter", "flow": "Payroll -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 9, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Performance', 'Performance challenge (AI-forward)', 'GlobalTech faces a AI-forward challenge in Performance. Your team must analyze and respond.', '[{"text": "Build a comprehensive AI-forward solution for Performance", "flow": "Performance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Performance to a specialist vendor", "flow": "Performance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Performance as-is, document improvement plan for next quarter", "flow": "Performance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 9, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('L&D', 'L&D challenge (AI-forward)', 'GlobalTech faces a AI-forward challenge in L&D. Your team must analyze and respond.', '[{"text": "Build a comprehensive AI-forward solution for L&D", "flow": "L&D -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource L&D to a specialist vendor", "flow": "L&D -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run L&D as-is, document improvement plan for next quarter", "flow": "L&D -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 9, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Compliance', 'Compliance challenge (AI-forward)', 'GlobalTech faces a AI-forward challenge in Compliance. Your team must analyze and respond.', '[{"text": "Build a comprehensive AI-forward solution for Compliance", "flow": "Compliance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Compliance to a specialist vendor", "flow": "Compliance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Compliance as-is, document improvement plan for next quarter", "flow": "Compliance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 9, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Employee Relations', 'Employee Relations challenge (AI-forward)', 'GlobalTech faces a AI-forward challenge in Employee Relations. Your team must analyze and respond.', '[{"text": "Build a comprehensive AI-forward solution for Employee Relations", "flow": "Employee Relations -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Employee Relations to a specialist vendor", "flow": "Employee Relations -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Employee Relations as-is, document improvement plan for next quarter", "flow": "Employee Relations -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 9, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Capstone', 'Capstone challenge (AI-forward)', 'GlobalTech faces a AI-forward challenge in Capstone. Your team must analyze and respond.', '[{"text": "Build a comprehensive AI-forward solution for Capstone", "flow": "Capstone -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Capstone to a specialist vendor", "flow": "Capstone -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Capstone as-is, document improvement plan for next quarter", "flow": "Capstone -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 9, (SELECT id FROM auth.users LIMIT 1));


-- ═══════════════════════════════════════
-- WEEK 10: Strategic HR & Board-Level
-- ═══════════════════════════════════════

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Workforce Planning', 'Workforce Planning challenge (board-ready)', 'GlobalTech faces a board-ready challenge in Workforce Planning. Your team must analyze and respond.', '[{"text": "Build a comprehensive board-ready solution for Workforce Planning", "flow": "Workforce Planning -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Workforce Planning to a specialist vendor", "flow": "Workforce Planning -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Workforce Planning as-is, document improvement plan for next quarter", "flow": "Workforce Planning -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 10, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Recruitment', 'Recruitment challenge (board-ready)', 'GlobalTech faces a board-ready challenge in Recruitment. Your team must analyze and respond.', '[{"text": "Build a comprehensive board-ready solution for Recruitment", "flow": "Recruitment -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Recruitment to a specialist vendor", "flow": "Recruitment -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Recruitment as-is, document improvement plan for next quarter", "flow": "Recruitment -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 10, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Onboarding', 'Onboarding challenge (board-ready)', 'GlobalTech faces a board-ready challenge in Onboarding. Your team must analyze and respond.', '[{"text": "Build a comprehensive board-ready solution for Onboarding", "flow": "Onboarding -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Onboarding to a specialist vendor", "flow": "Onboarding -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Onboarding as-is, document improvement plan for next quarter", "flow": "Onboarding -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 10, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Payroll', 'Payroll challenge (board-ready)', 'GlobalTech faces a board-ready challenge in Payroll. Your team must analyze and respond.', '[{"text": "Build a comprehensive board-ready solution for Payroll", "flow": "Payroll -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Payroll to a specialist vendor", "flow": "Payroll -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Payroll as-is, document improvement plan for next quarter", "flow": "Payroll -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 10, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Performance', 'Performance challenge (board-ready)', 'GlobalTech faces a board-ready challenge in Performance. Your team must analyze and respond.', '[{"text": "Build a comprehensive board-ready solution for Performance", "flow": "Performance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Performance to a specialist vendor", "flow": "Performance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Performance as-is, document improvement plan for next quarter", "flow": "Performance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 10, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('L&D', 'L&D challenge (board-ready)', 'GlobalTech faces a board-ready challenge in L&D. Your team must analyze and respond.', '[{"text": "Build a comprehensive board-ready solution for L&D", "flow": "L&D -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource L&D to a specialist vendor", "flow": "L&D -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run L&D as-is, document improvement plan for next quarter", "flow": "L&D -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 10, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Compliance', 'Compliance challenge (board-ready)', 'GlobalTech faces a board-ready challenge in Compliance. Your team must analyze and respond.', '[{"text": "Build a comprehensive board-ready solution for Compliance", "flow": "Compliance -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Compliance to a specialist vendor", "flow": "Compliance -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Compliance as-is, document improvement plan for next quarter", "flow": "Compliance -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 10, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Employee Relations', 'Employee Relations challenge (board-ready)', 'GlobalTech faces a board-ready challenge in Employee Relations. Your team must analyze and respond.', '[{"text": "Build a comprehensive board-ready solution for Employee Relations", "flow": "Employee Relations -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Employee Relations to a specialist vendor", "flow": "Employee Relations -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Employee Relations as-is, document improvement plan for next quarter", "flow": "Employee Relations -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 10, (SELECT id FROM auth.users LIMIT 1));

INSERT INTO custom_scenarios (module, title, description, options, week_number, created_by) VALUES
('Capstone', 'Capstone challenge (board-ready)', 'GlobalTech faces a board-ready challenge in Capstone. Your team must analyze and respond.', '[{"text": "Build a comprehensive board-ready solution for Capstone", "flow": "Capstone -> HRIS -> Analytics", "impact": {"hrEfficiency": 6, "talentQuality": 5, "budgetHealth": -6, "employeeTrust": 4}}, {"text": "Outsource Capstone to a specialist vendor", "flow": "Capstone -> Vendor Mgmt -> Finance", "impact": {"budgetHealth": 4, "hrEfficiency": 3, "talentQuality": -2, "legalSafety": -3}}, {"text": "Run Capstone as-is, document improvement plan for next quarter", "flow": "Capstone -> Operations", "impact": {"budgetHealth": 2, "hrEfficiency": -1, "employeeTrust": -2, "talentQuality": -3}}]', 10, (SELECT id FROM auth.users LIMIT 1));


-- Verify
SELECT week_number, COUNT(*) as scenarios FROM custom_scenarios GROUP BY week_number ORDER BY week_number;